version: '3'

services:
  es01-test:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana01-test:
    image: docker.elastic.co/kibana/kibana:7.15.0
    environment:
      ELASTICSEARCH_HOSTS: http://es01-test:9200
    ports:
      - "5601:5601"
#    volumes:
#      - "./data/mysql:/var/lib/mysql"
  mysql:
    image: mysql:5.6
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    environment:
      #MYSQL_ROOT_PASSWORD: mRVHePdfa4Z3X0ewfctefpZuqDrSbtINR4VRslgA2s
      MYSQL_ROOT_PASSWORD: root
      # time_zone +8
      TZ: Asia/Shanghai
    # For testing from the host:
    # mysql --host=127.0.0.1 --port=7033 --user root -p
    ports:
      - "3306:3306"
    volumes:
      - "./data/mysql:/var/lib/mysql"